### PR TITLE
Update ZEIT to front-end

### PR DESCRIPTION
**Pull request by msweeneydev**
Hey @stevekrouse, really enjoyed reading this and discovered a number of tools I'd not looked at before - thanks for putting it together!

This PR updates ZEIT to `front-end` rather than `back-end` as that's where our focus and core strengths are.

### CODE REVIEW

**Comment by stevekrouse** [comment]
Hey! Thanks for the pull request.

Could you help me understand why you want to update the tag to front-end? I can see how ZEIT is a really useful tool for building front-ends, and can be key for front-end developers by making back-ends really easy to build. Yet, ZEIT is still a platform for making serverless back-ends. What am I missing? Thanks!

**Comment by msweeneydev** [comment]
Hey Steven,

Thanks for getting back to me. I've had a chance to reflect on this and I think you've got a great point. Whilst our primary focus is frontend, we do have very strong support for Serverless Functions as well, thus providing a rich backend, just without all the configuration!

**Comment by stevekrouse** [comment]
Hey, thanks for the update. Will get that fixed. It looks like your editor reformatted a few files, and I feel a bit uncomfortable accepting so many changes from a stranger online. It'd be faster for me to make them myself I think that review all the lines. Sorry about that. Appreciate your help here!

**Comment by stevekrouse** [comment]
Closed https://github.com/stevekrouse/futureofcoding.org/commit/2f066843a430ba8f78b26bfaf249b12b2f46710e and https://github.com/stevekrouse/futureofcoding.org/commit/bb29be8ea905482545f01408a1e85fc02831cc3c

**Comment by msweeneydev** [comment]
Ah yes, I remember being careful the first time to avoid it but clearly not the second, apologies @stevekrouse!

Thanks for making those changes, much appreciated 👍

**Pull request closed without merging**
